#version: '3'
services:
  app1:
    build: .
    environment:
      - app_name=App-node1
    ports:
    - "3001:3000"
  
  app2:
    build: .
    environment:
      - app_name=App-node2
    ports:
    - "3002:3000"

  app3:
    build: .
    environment:
      - app_name=App-node3
    ports:
    - "3003:3000"

   