#version: '3'
services:
  nginx:
    image: nginx:latest
    volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
        - "80:80"
    depends_on:
      - app1
      - app2
      - app3

  app1:
    build: .
    environment:
      - app_name=App-node1
    ports:
    - "3001:3000"
  
  app2:
    build: .
    environment:
      - app_name=App-node2
    ports:
    - "3002:3000"

  app3:
    build: .
    environment:
      - app_name=App-node3
    ports:
    - "3003:3000"

   